export const AUTH_CONSTANTS = {
  VALIDATION: {
    PASSWORD_MIN_LENGTH: 12,
    MIN_AGE_YEARS: 10,
    EGYPTIAN_PHONE_REGEX: /^(01[0125][0-9]{8})$/,
    PASSWORD_UPPERCASE_REGEX: /[A-Z]/,
    PASSWORD_LOWERCASE_REGEX: /[a-z]/,
    PASSWORD_DIGIT_REGEX: /[0-9]/,
    PASSWORD_SPECIAL_REGEX: /[\W_]/,
  },
  KEYS: {
    REQUIRED_FIELD: 'AUTH.VALIDATION.REQUIRED',
    INVALID_EMAIL: 'AUTH.VALIDATION.INVALID_EMAIL',
    PASSWORD_WEAK: 'AUTH.VALIDATION.PASSWORD_WEAK',
    PASSWORD_MISMATCH: 'AUTH.VALIDATION.PASSWORD_MISMATCH',
    INVALID_PHONE: 'AUTH.VALIDATION.INVALID_PHONE',
    MIN_AGE_ERROR: 'AUTH.VALIDATION.MIN_AGE_ERROR',
    INVALID_DATE: 'AUTH.VALIDATION.INVALID_DATE',
    FUTURE_DATE: 'AUTH.VALIDATION.FUTURE_DATE',
    SAME_EMAIL_ERROR: 'AUTH.VALIDATION.SAME_EMAIL_ERROR',
  },
};

export type PasswordStrength = 'weak' | 'medium' | 'strong';
