const fs = require('fs');
const path = require('path');

const arPath = path.join(__dirname, '../src/assets/i18n/ar.json');
const enPath = path.join(__dirname, '../src/assets/i18n/en.json');

const ar = JSON.parse(fs.readFileSync(arPath, 'utf8'));
const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

const reportsKeysEn = {
  "TITLE": "Student Reports",
  "SELECT_CLASSROOM": "Select Classroom",
  "NO_STUDENTS": "No students in this classroom.",
  "EMPTY_TITLE": "Detailed Student Reports",
  "EMPTY_DESC": "Please select a classroom then a student from the sidebar to view their performance analytics and reports.",
  "ANALYTICS_OVERVIEW": "Analytics Overview",
  "OVERALL_AVERAGE": "Overall Average",
  "HIGHEST_SCORE": "Highest Score",
  "COMPLETED_EXAMS": "Completed Exams",
  "SUBJECT_PROFICIENCY": "Subject Proficiency",
  "NO_SUBJECTS": "No subject data available.",
  "LATEST_REPORT": "Latest Performance Report",
  "APPROVING": "Approving...",
  "APPROVE_SEND": "Approve & Send to Parent",
  "NO_LATEST_REPORT": "No performance report has been generated by AI yet.",
  "WEAK_TOPICS": "Weak Topics & Revision Areas",
  "SCORE": "Score",
  "INTERACTIVE_REVIEW": "Interactive Review",
  "PRACTICE_EXAM": "Practice Exam",
  "NO_WEAK_TOPICS": "Great Job!",
  "NO_WEAK_TOPICS_DESC": "No significant weak topics detected for this student."
};

const reportsKeysAr = {
  "TITLE": "تقارير الطلبة",
  "SELECT_CLASSROOM": "اختر الفصل",
  "NO_STUDENTS": "لا يوجد طلبة في هذا الفصل.",
  "EMPTY_TITLE": "تقارير الطلبة التفصيلية",
  "EMPTY_DESC": "يرجى اختيار فصل ثم اختيار أحد الطلبة من القائمة الجانبية لعرض تحليلات الأداء والتقارير الخاصة به.",
  "ANALYTICS_OVERVIEW": "نظرة عامة على الأداء",
  "OVERALL_AVERAGE": "المتوسط العام",
  "HIGHEST_SCORE": "أعلى درجة",
  "COMPLETED_EXAMS": "الامتحانات المكتملة",
  "SUBJECT_PROFICIENCY": "كفاءة المواد الدراسية",
  "NO_SUBJECTS": "لا توجد بيانات للمواد بعد.",
  "LATEST_REPORT": "أحدث تقرير أداء",
  "APPROVING": "جاري الاعتماد...",
  "APPROVE_SEND": "اعتماد التقرير وإرساله لولي الأمر",
  "NO_LATEST_REPORT": "لم يقم نظام الذكاء الاصطناعي بإصدار تقرير حديث لهذا الطالب حتى الآن.",
  "WEAK_TOPICS": "نقاط الضعف والمفاهيم المحتاجة للمراجعة",
  "SCORE": "الكفاءة",
  "INTERACTIVE_REVIEW": "مراجعة تفاعلية",
  "PRACTICE_EXAM": "امتحان تدريبي",
  "NO_WEAK_TOPICS": "عمل رائع!",
  "NO_WEAK_TOPICS_DESC": "لم يتم رصد أي نقاط ضعف جوهرية للطالب في الوقت الحالي."
};

if (!ar.TEACHER) ar.TEACHER = {};
ar.TEACHER.REPORTS = reportsKeysAr;

if (!en.TEACHER) en.TEACHER = {};
en.TEACHER.REPORTS = reportsKeysEn;

fs.writeFileSync(arPath, JSON.stringify(ar, null, 2), 'utf8');
fs.writeFileSync(enPath, JSON.stringify(en, null, 2), 'utf8');
console.log("Translations updated!");
